### ISSUE TITLE
Track progress in Issues so that the community can give back!

### ISSUE THREAD

**Issue by icorbrey** [cmstead/js-codeformer#1]
I would love if you tracked in-progress items in Issues so that community members (like myself) can help out with PRs, suggestions, and discussion.

**Comment by cmstead** [comment]
Cool, I can do that! Thanks!

**Comment by icorbrey** [comment]
Thank you!!

**Comment by cmstead** [comment]
Just as a quick update, I have created issues for each of the outstanding work items to be done (as listed in the readme). They can always be expanded, or modified as necessary.

**Comment by icorbrey** [comment]
Wonderful! Maybe some tags would be good as well, that way people can see what area things are in (e.g. new action behaviors, general chores, etc.)
