### ISSUE TITLE
Invert If

### ISSUE THREAD

**Issue by cmstead** [cmstead/js-codeformer#14]
Original issue on JS Refactor: https://github.com/cmstead/js-refactor/issues/109

One of my favorite refactors in Visual Studio was the Invert-if statement refactor:

if(someCondition){
..do a lot of work
}
return;
becomes

if(!someCondition){
  return
}
...do a lot of work

**Comment by cmstead** [comment]
This is complete in the latest release:

https://github.com/cmstead/js-codeformer/releases/tag/v1.2.1

**Comment by henrikrudstrom** [comment]
nice!
